FROM node:18

WORKDIR /app
COPY . .
RUN npm install react react-dom axios socket.io-client serve
RUN npm install --save-dev typescript @types/react @types/react-dom @babel/preset-typescript
RUN npx tsc
EXPOSE 3000
CMD ["npx", "serve", "-s", "dist"]